env:
  es6: true
  node: true
parser: babel-eslint
extends: plugin:meteor/recommended
plugins:
  - meteor
rules:
  meteor/template-names: off
  meteor/no-session: off
  indent:
    - error
    - 2
  max-len:
    - error
    - 80
    - 2
  object-curly-spacing:
    - error
    - always
  quotes:
    - error
    - single
  no-ternary: off
parserOptions:
  ecmaVersion: 2017
